{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getError"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"allocator","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The allocator to use for the error"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awscommonruntimekit\/crtawsendpointresolvedendpoint\/geterror()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AwsCommonRuntimeKit\/documentation\/AwsCommonRuntimeKit\/CRTAWSEndpointResolvedEndpoint\/getError()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get the error of the resolved endpoint"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getError"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"getError()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:19AwsCommonRuntimeKit30CRTAWSEndpointResolvedEndpointC8getErrorSSSgyKF","modules":[{"name":"AwsCommonRuntimeKit"}]},"hierarchy":{"paths":[["doc:\/\/AwsCommonRuntimeKit\/documentation\/AwsCommonRuntimeKit","doc:\/\/AwsCommonRuntimeKit\/documentation\/AwsCommonRuntimeKit\/CRTAWSEndpointResolvedEndpoint"]]},"references":{"doc://AwsCommonRuntimeKit/documentation/AwsCommonRuntimeKit":{"role":"collection","title":"AwsCommonRuntimeKit","abstract":[],"identifier":"doc:\/\/AwsCommonRuntimeKit\/documentation\/AwsCommonRuntimeKit","kind":"symbol","type":"topic","url":"\/documentation\/awscommonruntimekit"},"doc://AwsCommonRuntimeKit/documentation/AwsCommonRuntimeKit/CRTAWSEndpointResolvedEndpoint/getError()":{"role":"symbol","title":"getError()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getError"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the error of the resolved endpoint"}],"identifier":"doc:\/\/AwsCommonRuntimeKit\/documentation\/AwsCommonRuntimeKit\/CRTAWSEndpointResolvedEndpoint\/getError()","kind":"symbol","type":"topic","url":"\/documentation\/awscommonruntimekit\/crtawsendpointresolvedendpoint\/geterror()"},"doc://AwsCommonRuntimeKit/documentation/AwsCommonRuntimeKit/CRTAWSEndpointResolvedEndpoint":{"role":"symbol","title":"CRTAWSEndpointResolvedEndpoint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CRTAWSEndpointResolvedEndpoint"}],"abstract":[{"type":"text","text":"Resolved endpoint"}],"identifier":"doc:\/\/AwsCommonRuntimeKit\/documentation\/AwsCommonRuntimeKit\/CRTAWSEndpointResolvedEndpoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CRTAWSEndpointResolvedEndpoint"}],"url":"\/documentation\/awscommonruntimekit\/crtawsendpointresolvedendpoint"}}}